# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79c296ce034bbf0b7f02f71b5d60c75c49e9184fa3bff735f4a9708ff43efe2ee243d5225fd677630bd7ba57b3fc4c5419fafb56e6f73716ea065d6f5b083910

test:
  secret_key_base: cb808642239e43846fb2c5ea32eb2eaa26314280a910fc06fbf5646293a8419415f09b640765e8ef3b59128c6608ecb23d9b9dbe710a1c73b70f862d73e50164

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
